# MÓDULO: app.py | ES MI ARCHIVO PRINCIPAL.
"""ARCHIVO PRINCIPAL DEL PROGRAMA | EJECUTA EL MENÚ PRINCIPAL"""

from menu import ejecutar_menu # IMPORTO LA FUNCIÓN PRINCIPAL DEL MENÚ
ejecutar_menu() # INCIO DEL PROGRAMA.